package com.apple.spark.core;

import org.junit.runner.RunWith;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;

@RunWith(value = JUnitPlatform.class)
@SelectClasses(value = { ApplicationSubmissionHelper_getVolumes_5_0_Test.class, ApplicationSubmissionHelper_generateSubmissionId_7_0_Test.class, ApplicationSubmissionHelper_validateQueueToken_10_0_Test.class, ApplicationSubmissionHelper_getProxyUser_1_0_Test.class, ApplicationSubmissionHelper_getSparkConf_3_0_Test.class, ApplicationSubmissionHelper_parseSubmitRequest_0_0_Test.class, ApplicationSubmissionHelper_getDriverSpec_14_0_Test.class, ApplicationSubmissionHelper_generateSubmissionId_8_0_Test.class, ApplicationSubmissionHelper_getYuniKornSchedulerConfig_13_0_Test.class, ApplicationSubmissionHelper_getSparkUIConfiguration_4_0_Test.class, ApplicationSubmissionHelper_getType_23_0_Test.class, ApplicationSubmissionHelper_getExecutorSpec_22_0_Test.class, ApplicationSubmissionHelper_looksLikeFilePath_2_0_Test.class, ApplicationSubmissionHelper_populateEnv_6_0_Test.class, ApplicationSubmissionHelper_getClusterIdFromSubmissionId_9_0_Test.class })
public class ApplicationSubmissionHelper_Suite {
}
